apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}-config
  namespace: {{ .Values.namespace }}
data:
  MONGODB_URI: "{{ .Values.config.MONGODB_URI }}"
  NODE_ENV: "{{ .Values.config.NODE_ENV }}"
  NEXT_PUBLIC_API_URL: "{{ .Values.config.NEXT_PUBLIC_API_URL }}"
  NEXTAUTH_URL: "{{ .Values.config.NEXTAUTH_URL }}"
