apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.mongodb.name }}-pv
spec:
  capacity:
    storage: {{ .Values.mongodb.storage.size }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.mongodb.storage.path }}
  persistentVolumeReclaimPolicy: Retain
