apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  NEXTAUTH_SECRET: "{{ .Values.secrets.NEXTAUTH_SECRET }}"
  JWT_SECRET: "{{ .Values.secrets.JWT_SECRET }}"
