apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.mongodb.name }}
  namespace: {{ .Values.namespace }}
spec:
  serviceName: {{ .Values.mongodb.name }}-service
  replicas: {{ .Values.mongodb.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.mongodb.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.mongodb.name }}
    spec:
      containers:
        - name: {{ .Values.mongodb.name }}
          image: {{ .Values.mongodb.image }}
          ports:
            - containerPort: {{ .Values.mongodb.port }}
          resources:
            requests:
              memory: {{ .Values.mongodb.resources.requests.memory }}
              cpu: {{ .Values.mongodb.resources.requests.cpu }}
            limits:
              memory: {{ .Values.mongodb.resources.limits.memory }}
              cpu: {{ .Values.mongodb.resources.limits.cpu }}
          volumeMounts:
            - name: mongodb-storage
              mountPath: /data/db
  volumeClaimTemplates: []
  {{- if .Values.mongodb.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: mongodb-storage
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: {{ .Values.mongodb.persistence.size }}
        {{- if .Values.mongodb.persistence.storageClass }}
        storageClassName: {{ .Values.mongodb.persistence.storageClass }}
        {{- end }}
  {{- end }}
