name: easyshop
namespace: easyshop
replicaCount: 1
image:
  repository: ghcr.io/emmanuelogar/easyshop-app
  tag: "31"
  pullPolicy: Always
service:
  type: NodePort
  port: 80
  targetPort: 3000
  nodePort: 30000
ingress:
  enabled: true
  ingressClassName: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  host: easyshop.devdeploy.site
  tlsSecret: easyshop-tls
resources:
  requests:
    memory: "256Mi"
    cpu: "200m"
  limits:
    memory: "512Mi"
    cpu: "500m"
probes:
  startup:
    httpGet:
      path: /
      port: 3000
    failureThreshold: 30
    periodSeconds: 10
  readiness:
    httpGet:
      path: /
      port: 3000
    initialDelaySeconds: 20
    periodSeconds: 15
  liveness:
    httpGet:
      path: /
      port: 3000
    initialDelaySeconds: 25
    periodSeconds: 20
hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilization: 70
config:
  MONGODB_URI: "mongodb://mongodb-service:27017/easyshop"
  NODE_ENV: "production"
  NEXT_PUBLIC_API_URL: "https://easyshop.devdeploy.site/api"
  NEXTAUTH_URL: "https://easyshop.devdeploy.site/"
secrets:
  NEXTAUTH_SECRET: "change-this-in-production"
  JWT_SECRET: "change-this-in-production"
mongodb:
  name: mongodb
  replicas: 1
  image: mongo:latest
  port: 27017
  resources:
    requests:
      memory: "256Mi"
      cpu: "250m"
    limits:
      memory: "512Mi"
      cpu: "500m"
  persistence:
    enabled: true
    size: 5Gi
    storageClass: managed-csi
    pvcName: mongodb-pvc
migrationJob:
  enabled: true
  name: db-migration
  image: ghcr.io/emmanuelogar/easyshop-migration:31
  mongodbUri: "mongodb://mongodb-service:27017/easyshop"
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
