name: Run Tests

on:
  pull_request:
    branches: [ "main" ]

jobs:
  unit_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install dependencies
        run: npm ci   # faster & ensures clean lockfile install

      - name: Run tests
        run: npm test -- --run

      - name: Upload coverage report
        if: always() # ensure report uploads even if tests fail
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage
